### ISSUE TITLE
Getting events but not attendees still leads to "system is ready"

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#112]
For reference, something just broke rfidera, but regme still claims to be ready for use. Regme says so because it got the events, but the attendees aren't there, so we need to handle this case as an error. Sort of kind of critical, as this could cause mass confusion during an event. Considering the mail feedback we got from bedkom and fagkom, I believe this might actually have happened already.

**Comment by arwassa** [comment]
Fixed
