### ISSUE TITLE
Optimize API fetches

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#119]
This isn't critical or anything, but I believe right now we send a fetch for every attendance event we find after the initial fetch. This is unnecessary as regme is only opened for the sake of one particular event anyways. Well, if there are multiple attendance events then maybe they're using two events. Regardless, we should probably only load in the "first" event, then get the other data as they change events. It would probably get regme up and running faster, be less intense on OW4, and as long as the status field guides the users accordingly then it'll be a better experience overall.

**Comment by arwassa** [comment]
Addressed in PR #118
