### ISSUE TITLE
Company image in header during event

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#23]
It might look neat if the relevant company logos showed up in the header, opposite of the Online logo. We could find a way to make this work if several companies are tied to the event. If there are too many, maybe don't show any at all?

**Comment by arwassa** [comment]
Started working on this on the company-logo branch

**Comment by plusk** [comment]
@Aborysa how's that work working out? :construction_worker_man:

**Comment by plusk** [comment]
We did this! It looks awesome.
