### ISSUE TITLE
Fetch real data

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#37]
Just fetch once, then use async api-calls later

**Comment by sklirg** [comment]
Why would you download the data locally beforehand? You get the RFID tag as
input and POST it to the endpoint, temporary storing a list of users would
just generate more queries?

I'm not familiar with the existing solution, so if this is something that
already exists and therefore is required, of course, add it!

**Comment by myth** [comment]
That is what they mean/intend. The wording is just off.

**Comment by sklirg** [comment]
I was told personally. My bad.

**Comment by myth** [comment]
Ok, then they might have misunderstood. But from what i understood from last nights meeting, they seem to have a good grasp on what needs to be done.

**Comment by sklirg** [comment]
I meant I was updated on the case personally, with the same information you
presented here. 😊

**Comment by myth** [comment]
Ah, kek! :+1:

**Comment by plusk** [comment]
Yeah this is my bad, I copy pasted it wholesale from the todo we had on readme earlier. Chatted with sklirg myself regarding the issues just to inform him on the meeting last night.
