### ISSUE TITLE
Add progress bar to site

### ISSUE THREAD

**Issue by plusk** [dotkom/regme#49]
Rfidera has a neat progress bar that shows the loading of the app. While this oftentimes goes near instantly, it lets you know that the system is ready for use, which is handy feedback for the users.

**Comment by plusk** [comment]
We have a progress bar now, but to my knowledge it doesn't actually care about any progress, so it's just real pretty.

**Comment by OptimusCrime** [comment]
I like these two:
https://github.com/peachananr/loading-bar
https://github.com/chieffancypants/angular-loading-bar
